name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
  workflow_dispatch: # Allow to run workflow manually
    
jobs:
  edit_dockerhub_description:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      if: github.event_name != 'pull_request'
      with:
        username: ${{ secrets.EDIT_DOCKERHUB_DESCRIPTION_ACTION_DOCKERHUB_USERNAME }}
        password: ${{ secrets.EDIT_DOCKERHUB_DESCRIPTION_ACTION_DOCKERHUB_TOKEN }}
        repository: magic848/pornserv
        short-description: ${{ github.event.repository.description }}
        enable-url-completion: true
